# /admin/config.yml
backend:
  name: github
  repo: pbnjcat/personal-website
  branch: main
  base_url: sveltia-cms-auth.morphlingblade88.workers.dev

media_folder: "src/lib/assets/images"
public_folder: "/images"

collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: "src/lib/data/projects"
    extension: json
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "image", widget: "image" }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - { label: "Technologies", name: "tags", widget: "list", required: true }
      - { label: "Live Demo", name: "demo", widget: "string", required: false }
