# /admin/config.yml
backend:
  name: github
  repo: pbnjcat/personal-website
  branch: main
  base_url: https://sveltia-cms-auth.morphlingblade88.workers.dev
  skip_ci: true
logo_url: "favicon.svg"
media_folder: "src/lib/assets/images"

collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: "src/lib/data/projects"
    extension: json
    slug: "{{slug}}"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Thumbnail", name: "image", widget: "image" }
      - { label: "Date", name: startDate, widget: datetime, time_format: false }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: true,
        }
      - { label: "Live Demo", name: "demo", widget: "string", required: false }
